[Unit]
Requires=aibox-storage-init.service aibox-mariadb-init.service
After=aibox-storage-init.service aibox-mariadb-init.service

[Service]
ReadWritePaths=/userdata/aibox/database/mysql /userdata/aibox/logs/mysql
